# yamllint disable rule:document-start
# yamllint disable rule:line-length
# yamllint disable rule:braces

{{ $root := . }}
{{- range $index, $member := .Values.clusterMembers }}
{{- $namespace := include "rancher-cluster-templates.derivedNamespace" . }}
---
apiVersion: management.cattle.io/v3
clusterName: c-m-{{ trunc 8 (sha256sum (printf "%s/%s" $namespace $root.Values.cluster.name)) }}
kind: ClusterRoleTemplateBinding
metadata:
  name: ctrb-{{ trunc 8 (sha256sum (printf "%s/%s" $namespace $member.principalName )) }}
  namespace: c-m-{{ trunc 8 (sha256sum (printf "%s/%s" $namespace $root.Values.cluster.name)) }}
roleTemplateName: {{ $member.roleTemplateName }}
userPrincipalName: {{ $member.principalName }}
{{- end }}
