# yamllint disable rule:document-start
# yamllint disable rule:braces

{{- if .Values.addons.monitoring }}
{{- if eq .Values.addons.monitoring.enabled true }}
{{- $namespace := include "rancher-cluster-templates.derivedNamespace" $ }}
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: monitoring-crd-{{ .Values.cluster.name }}
  namespace: {{ $namespace }}
spec:
  chart: "rancher-monitoring-crd"
  repoName: "rancher-charts"
  releaseName: "rancher-monitoring-crd"
  version: {{ .Values.addons.monitoring.version }}
  {{- if .Values.addons.monitoring.values }}
  values:
{{ toYaml .Values.addons.monitoring.values | nindent 4 }}
  {{- end }}
  defaultNamespace: "cattle-monitoring-system"
  targets:
    - clusterName: {{ .Values.cluster.name }}
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: monitoring-{{ .Values.cluster.name }}
  namespace: {{ $namespace }}
spec:
  chart: "rancher-monitoring"
  repoName: "rancher-charts"
  releaseName: "rancher-monitoring"
  version: {{ .Values.addons.monitoring.version }}
  {{- if .Values.addons.monitoring.values }}
  values:
{{ toYaml .Values.addons.monitoring.values | nindent 4 }}
  {{- end }}
  defaultNamespace: "cattle-monitoring-system"
  targets:
    - clusterName: {{ .Values.cluster.name }}
  diff:
    comparePatches:
      - apiVersion: admissionregistration.k8s.io/v1beta1
        kind: MutatingWebhookConfiguration
        name: rancher-monitoring-admission
        jsonPointers:
          - /webhooks/0/failurePolicy
      - apiVersion: admissionregistration.k8s.io/v1beta1
        kind: ValidatingWebhookConfiguration
        name: rancher-monitoring-admission
        jsonPointers:
          - /webhooks/0/failurePolicy
      - apiVersion: monitoring.coreos.com/v1
        kind: ServiceMonitor
        name: rancher-monitoring-kubelet
        namespace: kube-system
        jsonPointers:
          - /spec/endpoints
{{- end }}
{{- end }}
