# yamllint disable rule:document-start
# yamllint disable rule:line-length
# yamllint disable rule:braces

{{- if eq .Values.cloudprovider "openstack" }}
{{- range $index, $nodepool := .Values.nodepools }}
{{- $namespace := include "rancher-cluster-templates.derivedNamespace" $ }}
---
apiVersion: rke-machine-config.cattle.io/v1
kind: OpenstackConfig
metadata:
  name: "{{ $.Values.cluster.name }}-{{ $nodepool.name }}"
  namespace: {{ $namespace }}

activeTimeout: {{ $nodepool.openstackconfig.activeTimeout | default "200" | quote }}

{{- $val := $.Values.cluster.config.openstack }}
{{- $secret := (lookup "v1" "Secret" $namespace $val.applicationCredentialSecretName) }}
{{/*If the values are defined in .Values.cluster.config.openstack.*, they are used directly. Otherwise, fall back to secret.*/}}
applicationCredentialId: {{- if $val.applicationCredentialId }}
  {{ $val.applicationCredentialId }}
  {{- else if and $secret $secret.data.applicationCredentialId }}
  {{ $secret.data.applicationCredentialId | b64dec }}
  {{- end }}
{{/*If the values are defined in .Values.cluster.config.openstack.*, they are used directly. Otherwise, fall back to secret.*/}}
applicationCredentialName: {{- if $val.applicationCredentialName }}
  {{ $val.applicationCredentialName }}
  {{- else if and $secret $secret.data.applicationCredentialName }}
  {{ $secret.data.applicationCredentialName | b64dec }}
  {{- end }}
{{/*If the values are defined in .Values.cluster.config.openstack.*, they are used directly. Otherwise, fall back to secret.*/}}
applicationCredentialSecret: {{- if $val.applicationCredentialSecret }}
  {{ $val.applicationCredentialSecret }}
  {{- else if and $secret $secret.data.applicationCredentialSecret }}
  {{ $secret.data.applicationCredentialSecret | b64dec }}
  {{- end }}

authUrl: {{ $.Values.cluster.config.openstack.authUrl }}

keypairName: {{ $.Values.cluster.config.openstack.defaultKeypairName }}

{{ if lookup "v1" "Secret" $namespace $.Values.cluster.config.openstack.defaultPrivateKeyFileSecretName }}
privateKeyFile: | {{ (lookup "v1" "Secret" $namespace $.Values.cluster.config.openstack.defaultPrivateKeyFileSecretName).data.privateKeyFile | b64dec | nindent 4 }}
{{- end }}

region: {{ $.Values.cluster.config.openstack.region }}

secGroups: {{ $.Values.cluster.config.openstack.secGroups }}

sshPort: {{ $.Values.cluster.config.openstack.sshPort | quote}}

sshUser: {{ $.Values.cluster.config.openstack.sshUser }}

{{- if eq $index 0 }}
flavorName: {{ $.Values.cluster.config.openstack.masterFlavorName }}
  {{- if $.Values.cluster.config.openstack.masterFlavorId }}
flavorId: {{ $.Values.cluster.config.openstack.masterFlavorId }}
  {{- end }}
{{- else }}
flavorName: {{ $.Values.cluster.config.openstack.workerFlavorName }}
  {{- if $.Values.cluster.config.openstack.workerFlavorId }}
flavorId: {{ $.Values.cluster.config.openstack.workerFlavorId }}
  {{- end }}
{{- end }}

floatingipPool: {{ $.Values.cluster.config.openstack.floatingipPool }}

netName: {{ $.Values.cluster.config.openstack.netName }}
{{- if  $.Values.cluster.config.openstack.netId }}
netId: {{ $.Values.cluster.config.openstack.netId }}
{{- end }}

imageName: {{ $.Values.cluster.config.openstack.imageName }}
{{- if $.Values.cluster.config.openstack.imageId }}
imageId: {{ $.Values.cluster.config.openstack.imageId }}
{{- end }}

{{- if $nodepool.openstackconfig.availabilityZone }}
availabilityZone: {{ $nodepool.openstackconfig.availabilityZone }}
{{- end }}
{{- if $nodepool.openstackconfig.bootFromVolume }}
bootFromVolume: {{ $nodepool.openstackconfig.bootFromVolume }}
{{- end }}
{{- if $nodepool.openstackconfig.cacert }}
cacert: {{ $nodepool.openstackconfig.cacert }}
{{- end }}
{{- if $nodepool.openstackconfig.configDrive }}
configDrive: {{ $nodepool.openstackconfig.configDrive }}
{{- end }}
{{- if $nodepool.openstackconfig.domainId }}
domainId: {{ $nodepool.openstackconfig.domainId }}
{{- end }}
{{- if $nodepool.openstackconfig.domainName }}
domainName: {{ $nodepool.openstackconfig.domainName | default "default" }}
{{- end }}
{{- if $nodepool.openstackconfig.endpointType }}
endpointType: {{ $nodepool.openstackconfig.endpointType }}
{{- end }}
{{- if $nodepool.openstackconfig.insecure }}
insecure: {{ $nodepool.openstackconfig.insecure }}
{{- end }}
ipVersion: "{{ $nodepool.openstackconfig.ipVersion | default "4" }}"
novaNetwork: {{ $nodepool.openstackconfig.novaNetwork | default false}}
{{- if $nodepool.openstackconfig.tenantDomainId }}
tenantDomainId: {{ $nodepool.openstackconfig.tenantDomainId  }}
{{- end }}
{{- if $nodepool.openstackconfig.tenantDomainName }}
tenantDomainName: {{ $nodepool.openstackconfig.tenantDomainName }}
{{- end }}
{{- if $nodepool.openstackconfig.tenantId }}
tenantId: {{ $nodepool.openstackconfig.tenantId }}
{{- end }}
{{- if $nodepool.openstackconfig.tenantName }}
tenantName: {{ $nodepool.openstackconfig.tenantName }}
{{- end }}
{{- if $nodepool.openstackconfig.userDataFile }}
userDataFile: | {{ $nodepool.openstackconfig.userDataFile | nindent 4 }}
{{- end }}
{{- if $nodepool.openstackconfig.userDomainId }}
userDomainId: {{ $nodepool.openstackconfig.userDomainId }}
{{- end }}
{{- if $nodepool.openstackconfig.userDomainName }}
userDomainName: {{ $nodepool.openstackconfig.userDomainName }}
{{- end }}
{{- if $nodepool.openstackconfig.userId }}
userId: {{ $nodepool.openstackconfig.userId }}
{{- end }}
{{- if $nodepool.openstackconfig.username }}
username: {{ $nodepool.openstackconfig.username }}
{{- end }}
{{- if $nodepool.openstackconfig.volumeDevicePath }}
volumeDevicePath: {{ $nodepool.openstackconfig.volumeDevicePath }}
{{- end }}
{{- if $nodepool.openstackconfig.volumeId }}
volumeId: {{ $nodepool.openstackconfig.volumeId }}
{{- end }}
{{- if $nodepool.openstackconfig.volumeName }}
volumeName: {{ $nodepool.openstackconfig.volumeName }}
{{- end }}
{{- if $nodepool.openstackconfig.volumeSize }}
volumeSize: "{{ $nodepool.openstackconfig.volumeSize }}"
{{- end }}
{{- if $nodepool.openstackconfig.volumeType }}
volumeType: {{ $nodepool.openstackconfig.volumeType }}
{{- end }}

{{- end }}
{{- end }}
