# yamllint disable rule:document-start
# yamllint disable rule:line-length

{{- $namespace := include "rancher-cluster-templates.derivedNamespace" $ }}
{{- $suffix := include "rancher-cluster-templates.randomString" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-cloud-config-{{ $suffix }}
  namespace: {{$namespace}}
  annotations:
    rke.cattle.io/object-authorized-for-clusters: {{ .Values.cluster.name }}
    #provisioning.cattle.io/owned-by: {{ printf "%s/%s" $namespace .Values.cluster.name }}
type: Opaque
stringData:
  cloud.conf: |
{{ include "rancher-cluster-templates.cloudConfig" . | indent 4 }}